apiVersion: v1
kind: Service
metadata:
  name: rancher-service
  namespace: cattle-system
  labels: 
    app: rancher
spec:
  type: NodePort
  selector:
    app: rancher
  ports:
    - name: rancher-port
      protocol: TCP
      port: 443
      nodePort: 31443
