apiVersion: v1
kind: Service
metadata:
  name: redmine-postgresql-service
  labels: 
    app: redmine-postgresql
spec:
  type: NodePort
  selector:
    app: redmine-postgresql
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      nodePort: 32749
