apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  labels: 
    app: gitlab
spec:
  type: ClusterIP
  selector:
    app: gitlab
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      #nodePort: 32748
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
      #nodePort: 32748
