apiVersion: v1
kind: Service
metadata:
  name: gitlab-service
  labels: 
    app: gitlab
spec:
  type: NodePort
  selector:
    app: gitlab
  ports:
    - name: http
      protocol: TCP
      port: 32080
      nodePort: 32080