apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: devopsapi-rel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsapi-rel
  template:
    metadata:
      labels:
        app: devopsapi-rel
    spec:
      containers:
      - name: devopsapi-rel
        image: iiiorg/devops-db-rel
        imagePullPolicy: Always
        ports:
        - containerPort: 10009
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://postgres:openstack@140.92.4.5:31404/devopsdb"
        - name: SQLALCHEMY_TRACK_MODIFICATIONS
          value: "false"
        - name: JWT_SECRET_KEY
          value: "iii-devops"
        - name: WTF_CSRF_CHECK_DEFAULT
          value: "false"
        - name: JSON_AS_ASCII
          value: "false"
        - name: REDMINE_IP_PORT
          value: "140.92.4.5:32748"
        - name: REDMINE_ADMIN_ACCOUNT
          value: "admin"
        - name: REDMINE_ADMIN_PASSWORD
          value: "qazwsxedc"
        - name: REDMINE_API_KEY
          value: 6f1bcd77154abdd0ffaeb32221f255e4ff838070
        - name: GITLAB_IP_PORT
          value: 140.92.4.3
        - name: GITLAB_ADMIN_ACCOUNT
          value: root
        - name: GITLAB_ADMIN_PASSWORD
          value: qazwsxedc
        - name: GITLAB_PRIVATE_TOKEN
          value: bZJzEyp1tQNyDxyuhfDT
        - name: RANCHER_IP_PORT
          value: 140.92.4.4
        - name: RANCHER_ADMIN_ACCOUNT
          value: admin
        - name: RANCHER_ADMIN_PASSWORD
          value: qazwsxedc
        - name: RANCHER_CLUSTER_NAME
          value: iiidevops-k8s
        - name: CHECKMARX_ORIGIN
          value: https://checkmarx.labad.org/cxrestapi
        - name: CHECKMARX_USERNAME
          value: dtiuser
        - name: CHECKMARX_PASSWORD
          value: IIIdevops123!
        - name: CHECKMARX_SECRET
          value: 014DF517-39D1-4453-B7B3-9930C563627C
        - name: SONAR_IP_PORT
          value: 140.92.4.5:31910
        - name: HARBOR_BASE_URL
          value: https://140.92.4.3:5443/api/v2.0
        - name: HARBOR_ACCOUNT
          value: "admin"
        - name: HARBOR_PASSWORD
          value: "!QAZ2wsx3edc"
