apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: devopsapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsapi
  template:
    metadata:
      labels:
        app: devopsapi
    spec:
      containers:
      - name: devopsapi
        image: iiiorg/devops-api:0cb6e72-10121141
        ports:
        - containerPort: 10009
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "postgresql://postgres:xxxxxxxx@140.92.4.5:31403/devopsdb"
        - name: SQLALCHEMY_TRACK_MODIFICATIONS
          value: "false"
        - name: JWT_SECRET_KEY
          value: "xxxxxxxx"
        - name: WTF_CSRF_CHECK_DEFAULT
          value: "false"
        - name: JSON_AS_ASCII
          value: "false"
        - name: REDMINE_IP_PORT
          value: "140.92.4.5:32748"
        - name: REDMINE_ADMIN_ACCOUNT
          value: "admin"
        - name: REDMINE_ADMIN_PASSWORD
          value: "xxxxxxxx"
        - name: REDMINE_API_KEY
          value: xxxxxxxx
        - name: GITLAB_IP_PORT
          value: 140.92.4.3
        - name: GITLAB_ADMIN_ACCOUNT
          value: root
        - name: GITLAB_ADMIN_PASSWORD
          value: xxxxxxxx
        - name: GITLAB_PRIVATE_TOKEN
          value: xxxxxxxx
        - name: RANCHER_IP_PORT
          value: 140.92.4.4
        - name: RANCHER_ADMIN_ACCOUNT
          value: admin
        - name: RANCHER_ADMIN_PASSWORD
          value: xxxxxxxx
        - name: RANCHER_CLUSTER_NAME
          value: iiidevops-k8s
        - name: CHECKMARX_ORIGIN
          value: https://checkmarx.labad.org/cxrestapi
        - name: CHECKMARX_USERNAME
          value: dtiuser
        - name: CHECKMARX_PASSWORD
          value: xxxxxxxx
        - name: CHECKMARX_SECRET
          value: 014DF517-39D1-4453-B7B3-9930C563627C
        - name: SONAR_IP_PORT
          value: 140.92.4.5:31910
