apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: devopsui-rel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devopsui-rel
  template:
    metadata:
      labels:
        app: devopsui-rel
    spec:
      containers:
      - name: devopsui-rel
        image: iiiorg/devops-ui:rel-54e2d24
        ports:
        - containerPort: 80
