apiVersion: v1
kind: Service
metadata:
  name: sonarqube-postgresql-service
  labels: 
    app: sonarqube-postgresql
spec:
  type: NodePort
  selector:
    app: sonarqube-postgresql
  ports:
    - name: postgres
      protocol: TCP
      port: 5432
      nodePort: 32750
